import Database from "better-sqlite3";
import { describe, expect, it } from "vitest";
import { applyMigrations } from "../src/migrations.js";
import { db, getSchemaVersion, listSchemaMigrations } from "../src/db.js";

describe("database schema migrations",()=>{
  it("records the current schema version and migration history",()=>{expect(getSchemaVersion()).toBe(13);expect(listSchemaMigrations()).toEqual([expect.objectContaining({version:1,name:"initial-factory-schema"}),expect.objectContaining({version:2,name:"repair-legacy-factory-schema"}),expect.objectContaining({version:3,name:"engineering-and-work-order-schema"}),expect.objectContaining({version:4,name:"factory-cycle-lineage"}),expect.objectContaining({version:5,name:"versioned-engineering-records"}),expect.objectContaining({version:6,name:"artifact-revision-history"}),expect.objectContaining({version:7,name:"engineering-knowledge-base"}),expect.objectContaining({version:8,name:"evidence-and-provenance"}),expect.objectContaining({version:9,name:"bom-and-component-lifecycle"}),expect.objectContaining({version:10,name:"supplier-discovery-and-approved-sources"}),expect.objectContaining({version:11,name:"change-impact-and-design-review-gates"}),expect.objectContaining({version:12,name:"normalize-legacy-requirements"}),expect.objectContaining({version:13,name:"project-lifecycle-stages"})]);});
  it("exposes the complete factory persistence schema",()=>{const tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all() as Array<{name:string}>;expect(tables.map(t=>t.name)).toEqual(expect.arrayContaining(["projects","runs","events","approvals","requirements","artifacts","artifact_links","engineering_requirements","engineering_plans","fusion_links","verification_records","work_orders","factory_cycles","requirement_revisions","engineering_facts","artifact_revisions","materials","components","standards","manufacturing_constraints","evidence_sources","evidence_claims","bom_revisions","bom_items","component_lifecycle_events","suppliers","supplier_offers","approved_sources","requirement_artifact_links","impact_analyses","impact_items","design_reviews","design_review_findings","project_stages","schema_migrations"]));const requirements=db.prepare("PRAGMA table_info(requirements)").all() as Array<{name:string}>;const artifacts=db.prepare("PRAGMA table_info(artifacts)").all() as Array<{name:string}>;const runs=db.prepare("PRAGMA table_info(runs)").all() as Array<{name:string}>;const events=db.prepare("PRAGMA table_info(events)").all() as Array<{name:string}>;expect(requirements.map(c=>c.name)).toEqual(expect.arrayContaining(["source","key","value","created_at","updated_at"]));expect(artifacts.map(c=>c.name)).toEqual(expect.arrayContaining(["run_id","parent_artifact_id","metadata","created_at"]));expect(runs.map(c=>c.name)).toContain("cycle_id");expect(events.map(c=>c.name)).toContain("cycle_id");});
  it("repairs a legacy database that incorrectly claims version 1",()=>{const legacy=new Database(":memory:");legacy.exec(`CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL);CREATE TABLE requirements(id TEXT PRIMARY KEY,project_id TEXT NOT NULL);CREATE TABLE artifacts(id TEXT PRIMARY KEY,project_id TEXT NOT NULL);INSERT INTO schema_migrations VALUES(1,'initial-factory-schema','2026-01-01T00:00:00.000Z');`);applyMigrations(legacy);const requirementColumns=legacy.prepare("PRAGMA table_info(requirements)").all() as Array<{name:string}>;const artifactColumns=legacy.prepare("PRAGMA table_info(artifacts)").all() as Array<{name:string}>;expect(requirementColumns.map(c=>c.name)).toEqual(expect.arrayContaining(["source","key","value","created_at","updated_at"]));expect(artifactColumns.map(c=>c.name)).toEqual(expect.arrayContaining(["run_id","parent_artifact_id","metadata","created_at"]));expect(legacy.prepare("SELECT version FROM schema_migrations ORDER BY version").all()).toEqual([{version:1},{version:2},{version:3},{version:4},{version:5},{version:6},{version:7},{version:8},{version:9},{version:10},{version:11},{version:12},{version:13}]);expect((legacy.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='design_reviews'").get() as {name:string}).name).toBe("design_reviews");expect((legacy.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='project_stages'").get() as {name:string}).name).toBe("project_stages");legacy.close();});
});
