import Database from "better-sqlite3";
import { describe, expect, it } from "vitest";
import { applyMigrations } from "../src/migrations.js";
import { db, getSchemaVersion, listSchemaMigrations } from "../src/db.js";

describe("database schema migrations",()=>{
  it("records the current schema version and migration history",()=>{expect(getSchemaVersion()).toBe(6);expect(listSchemaMigrations()).toEqual([expect.objectContaining({version:1,name:"initial-factory-schema"}),expect.objectContaining({version:2,name:"repair-legacy-factory-schema"}),expect.objectContaining({version:3,name:"engineering-and-work-order-schema"}),expect.objectContaining({version:4,name:"factory-cycle-lineage"}),expect.objectContaining({version:5,name:"versioned-engineering-records"}),expect.objectContaining({version:6,name:"artifact-revision-history"})]);});
  it("exposes the complete factory persistence schema",()=>{const tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all() as Array<{name:string}>;expect(tables.map(t=>t.name)).toEqual(expect.arrayContaining(["projects","runs","events","approvals","requirements","artifacts","artifact_links","engineering_requirements","engineering_plans","fusion_links","verification_records","work_orders","factory_cycles","requirement_revisions","engineering_facts","artifact_revisions","schema_migrations"]));const requirements=db.prepare("PRAGMA table_info(requirements)").all() as Array<{name:string}>;const artifacts=db.prepare("PRAGMA table_info(artifacts)").all() as Array<{name:string}>;const runs=db.prepare("PRAGMA table_info(runs)").all() as Array<{name:string}>;const events=db.prepare("PRAGMA table_info(events)").all() as Array<{name:string}>;expect(requirements.map(c=>c.name)).toEqual(expect.arrayContaining(["source","key","value","created_at","updated_at"]));expect(artifacts.map(c=>c.name)).toEqual(expect.arrayContaining(["run_id","parent_artifact_id","metadata","created_at"]));expect(runs.map(c=>c.name)).toContain("cycle_id");expect(events.map(c=>c.name)).toContain("cycle_id");});
  it("repairs a legacy database that incorrectly claims version 1",()=>{const legacy=new Database(":memory:");legacy.exec(`CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL);CREATE TABLE requirements(id TEXT PRIMARY KEY,project_id TEXT NOT NULL);CREATE TABLE artifacts(id TEXT PRIMARY KEY,project_id TEXT NOT NULL);INSERT INTO schema_migrations VALUES(1,'initial-factory-schema','2026-01-01T00:00:00.000Z');`);applyMigrations(legacy);const requirementColumns=legacy.prepare("PRAGMA table_info(requirements)").all() as Array<{name:string}>;const artifactColumns=legacy.prepare("PRAGMA table_info(artifacts)").all() as Array<{name:string}>;expect(requirementColumns.map(c=>c.name)).toEqual(expect.arrayContaining(["source","key","value","created_at","updated_at"]));expect(artifactColumns.map(c=>c.name)).toEqual(expect.arrayContaining(["run_id","parent_artifact_id","metadata","created_at"]));expect(legacy.prepare("SELECT version FROM schema_migrations ORDER BY version").all()).toEqual([{version:1},{version:2},{version:3},{version:4},{version:5},{version:6}]);legacy.close();});
});
