import type { FastifyInstance } from "fastify";
import { getProject } from "./db.js";
import { BomItem, ComponentLifecycle, createBomRevision, getBomRevision, listBomRevisions, setBomRevisionStatus, recordComponentLifecycle, listComponentLifecycle, getApprovedBom } from "./bom.js";

export async function registerBomRoutes(app: FastifyInstance) {
  app.get("/api/projects/:id/boms", async (request, reply) => { const {id}=request.params as {id:string}; if(!getProject(id))return reply.code(404).send({error:"project not found"}); return listBomRevisions(id); });
  app.get("/api/projects/:id/boms/approved", async (request, reply) => { const {id}=request.params as {id:string}; if(!getProject(id))return reply.code(404).send({error:"project not found"}); return getApprovedBom(id); });
  app.post("/api/projects/:id/boms", async (request, reply) => { const {id}=request.params as {id:string}; if(!getProject(id))return reply.code(404).send({error:"project not found"}); try { const body=request.body as {items?:unknown[];reason?:string;workOrderId?:string}; if(!Array.isArray(body.items)||!body.reason)return reply.code(400).send({error:"items and reason are required"}); const parsed=body.items.map(item=>BomItem.parse(item)); return reply.code(201).send(getBomRevision(createBomRevision(id,parsed,body.reason,body.workOrderId))); } catch(error){return reply.code(400).send({error:String(error)});} });
  app.get("/api/boms/:id", async (request, reply) => { const {id}=request.params as {id:string}; const bom=getBomRevision(id); if(!bom)return reply.code(404).send({error:"BOM revision not found"}); return bom; });
  app.patch("/api/boms/:id/status", async (request, reply) => { const {id}=request.params as {id:string}; const body=request.body as {status?:string}; const status=ComponentLifecycle.safeParse(body?.status); if(status.success)return reply.code(400).send({error:"invalid BOM status"}); if(!body?.status||!(["draft","approved","superseded","rejected"] as string[]).includes(body.status))return reply.code(400).send({error:"status must be draft, approved, superseded, or rejected"}); try{setBomRevisionStatus(id,body.status as "draft"|"approved"|"superseded"|"rejected"); return getBomRevision(id);}catch(error){return reply.code(400).send({error:String(error)});} });
  app.get("/api/projects/:id/components/:componentId/lifecycle", async (request, reply) => { const {id,componentId}=request.params as {id:string;componentId:string}; if(!getProject(id))return reply.code(404).send({error:"project not found"}); try{return listComponentLifecycle(id,componentId);}catch(error){return reply.code(404).send({error:String(error)});} });
  app.post("/api/projects/:id/components/:componentId/lifecycle", async (request, reply) => { const {id,componentId}=request.params as {id:string;componentId:string}; if(!getProject(id))return reply.code(404).send({error:"project not found"}); const body=request.body as {status?:string;reason?:string;evidenceClaimId?:string}; const status=ComponentLifecycle.safeParse(body?.status); if(!status.success||!body.reason)return reply.code(400).send({error:"status and reason are required"}); try{return{id:recordComponentLifecycle(id,componentId,status.data,body.reason,body.evidenceClaimId)}}catch(error){return reply.code(400).send({error:String(error)});} });
}
