import { z } from "zod";
import { randomUUID } from "node:crypto";
import { db } from "./db.js";

export const BomItem = z.object({ partNumber:z.string().min(1), name:z.string().min(1), quantity:z.number().positive(), material:z.string().optional(), source:z.enum(["designed","purchased","reused"]).default("designed"), notes:z.string().optional(), componentId:z.string().optional(), position:z.record(z.string(),z.number()).optional() });
export const WorkOrder = z.object({ id:z.string(), projectId:z.string(), objective:z.string(), status:z.enum(["draft","awaiting_approval","approved","rejected","completed"]).default("draft"), bom:z.array(BomItem), manufacturingNotes:z.array(z.string()).default([]) });
export type BomItem = z.infer<typeof BomItem>;
export const ComponentLifecycle = z.enum(["active","nrnd","obsolete","unknown"]);
export type ComponentLifecycle = z.infer<typeof ComponentLifecycle>;

export function createWorkOrder(projectId:string, objective:string, bom:BomItem[], manufacturingNotes:string[]=[]){ const id=`WO-${randomUUID().slice(0,8)}`; const now=new Date().toISOString(); db.prepare(`INSERT INTO work_orders(id,project_id,objective,status,bom_json,notes_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,projectId,objective,"awaiting_approval",JSON.stringify(bom),JSON.stringify(manufacturingNotes),now,now); return getWorkOrder(id); }
export function getWorkOrder(id:string){ const row=db.prepare(`SELECT * FROM work_orders WHERE id=?`).get(id) as any; if(!row)return null; return WorkOrder.parse({id:row.id,projectId:row.project_id,objective:row.objective,status:row.status,bom:JSON.parse(row.bom_json),manufacturingNotes:JSON.parse(row.notes_json)}); }
export function listWorkOrders(projectId?:string){ const rows=projectId?db.prepare(`SELECT * FROM work_orders WHERE project_id=? ORDER BY created_at DESC`).all(projectId):db.prepare(`SELECT * FROM work_orders ORDER BY created_at DESC`).all(); return rows.map((row:any)=>WorkOrder.parse({id:row.id,projectId:row.project_id,objective:row.objective,status:row.status,bom:JSON.parse(row.bom_json),manufacturingNotes:JSON.parse(row.notes_json)})); }

function assertProjectComponent(projectId:string,componentId:string){const component=db.prepare(`SELECT * FROM components WHERE id=? AND project_id=?`).get(componentId,projectId) as {id:string;part_number:string;name:string;lifecycle:ComponentLifecycle}|undefined;if(!component)throw new Error("component not found in project");return component;}
export function createBomRevision(projectId:string,items:BomItem[],reason:string,workOrderId?:string){if(!reason.trim())throw new Error("BOM revision reason is required");const versionRow=db.prepare(`SELECT COALESCE(MAX(version),0) AS version FROM bom_revisions WHERE project_id=?`).get(projectId) as {version:number};const version=versionRow.version+1;const id=`BOM-${randomUUID().slice(0,8)}`;const now=new Date().toISOString();const parsed=items.map(item=>BomItem.parse(item));for(const item of parsed)if(item.componentId)assertProjectComponent(projectId,item.componentId);const tx=db.transaction(()=>{db.prepare(`INSERT INTO bom_revisions(id,project_id,work_order_id,version,status,reason,created_at) VALUES(?,?,?,?,?,?,?)`).run(id,projectId,workOrderId??null,version,"draft",reason,now);const insert=db.prepare(`INSERT INTO bom_items(id,bom_revision_id,component_id,part_number,name,quantity,unit,source,notes,position_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`);for(const item of parsed)insert.run(randomUUID(),id,item.componentId??null,item.partNumber,item.name,item.quantity,"each",item.source,item.notes??null,item.position?JSON.stringify(item.position):null,now);});tx();return id;}
export function getBomRevision(id:string){const revision=db.prepare(`SELECT * FROM bom_revisions WHERE id=?`).get(id) as any;if(!revision)return null;const items=db.prepare(`SELECT * FROM bom_items WHERE bom_revision_id=? ORDER BY rowid ASC`).all(id) as any[];return{...revision,items:items.map(item=>({...item,position_json:item.position_json?JSON.parse(item.position_json):null}))};}
export function listBomRevisions(projectId:string){return(db.prepare(`SELECT * FROM bom_revisions WHERE project_id=? ORDER BY version DESC`).all(projectId) as any[]).map(revision=>({...revision,items:db.prepare(`SELECT * FROM bom_items WHERE bom_revision_id=? ORDER BY rowid ASC`).all(revision.id)}));}
export function setBomRevisionStatus(id:string,status:"draft"|"approved"|"superseded"|"rejected"){const revision=db.prepare(`SELECT * FROM bom_revisions WHERE id=?`).get(id) as any;if(!revision)throw new Error("BOM revision not found");if(status==="approved"){const current=db.prepare(`SELECT id FROM bom_revisions WHERE project_id=? AND status='approved' AND id<>?`).all(revision.project_id,id) as Array<{id:string}>;const tx=db.transaction(()=>{db.prepare(`UPDATE bom_revisions SET status='superseded' WHERE project_id=? AND status='approved' AND id<>?`).run(revision.project_id,id);db.prepare(`UPDATE bom_revisions SET status='approved' WHERE id=?`).run(id);});tx();}else db.prepare(`UPDATE bom_revisions SET status=? WHERE id=?`).run(status,id);}
export function recordComponentLifecycle(projectId:string,componentId:string,toStatus:ComponentLifecycle,reason:string,evidenceClaimId?:string){const component=assertProjectComponent(projectId,componentId);if(!reason.trim())throw new Error("lifecycle reason is required");if(component.lifecycle===toStatus)return null;const id=randomUUID(),now=new Date().toISOString();const tx=db.transaction(()=>{db.prepare(`UPDATE components SET lifecycle=?,updated_at=? WHERE id=? AND project_id=?`).run(toStatus,now,componentId,projectId);db.prepare(`INSERT INTO component_lifecycle_events(id,project_id,component_id,from_status,to_status,reason,evidence_claim_id,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,projectId,componentId,component.lifecycle,toStatus,reason,evidenceClaimId??null,now);});tx();return id;}
export function listComponentLifecycle(projectId:string,componentId:string){assertProjectComponent(projectId,componentId);return db.prepare(`SELECT * FROM component_lifecycle_events WHERE project_id=? AND component_id=? ORDER BY created_at ASC`).all(projectId,componentId);}
export function getApprovedBom(projectId:string){const revision=db.prepare(`SELECT * FROM bom_revisions WHERE project_id=? AND status='approved' ORDER BY version DESC LIMIT 1`).get(projectId) as any;if(!revision)return null;return getBomRevision(revision.id);}
