import { fusion } from "./fusion.js";
import { withTimeout } from "./execution.js";
import { config } from "./config.js";
export type CreateBoxArgs={widthMm:number;depthMm:number;heightMm:number};export type CreateCylinderArgs={radiusMm:number;heightMm:number};export type CreateMountingPlateArgs={widthMm:number;depthMm:number;plateHeightMm:number;postRadiusMm:number;postHeightMm:number;insetMm:number};export type CreateEnclosureArgs={widthMm:number;depthMm:number;baseHeightMm:number;wallHeightMm:number;wallThicknessMm:number};export type CadResult={success:boolean;operation:"create_box"|"create_cylinder"|"create_mounting_plate"|"create_enclosure";dimensionsMm?:{width:number;depth:number;height:number};radiusMm?:number;bodies?:number;document?:string;error?:string};
function finitePositive(value:unknown,name:string){if(typeof value!=="number"||!Number.isFinite(value)||value<=0)throw new Error(`${name} must be a positive finite number.`);if(value>10_000)throw new Error(`${name} exceeds the 10,000 mm safety limit.`);return value;}
export function parseCreateBoxArgs(args:Record<string,unknown>):CreateBoxArgs{return{widthMm:finitePositive(args.widthMm,"widthMm"),depthMm:finitePositive(args.depthMm,"depthMm"),heightMm:finitePositive(args.heightMm,"heightMm")};}
export function parseCreateCylinderArgs(args:Record<string,unknown>):CreateCylinderArgs{return{radiusMm:finitePositive(args.radiusMm,"radiusMm"),heightMm:finitePositive(args.heightMm,"heightMm")};}
export function parseCreateMountingPlateArgs(args:Record<string,unknown>):CreateMountingPlateArgs{const parsed={widthMm:finitePositive(args.widthMm,"widthMm"),depthMm:finitePositive(args.depthMm,"depthMm"),plateHeightMm:finitePositive(args.plateHeightMm,"plateHeightMm"),postRadiusMm:finitePositive(args.postRadiusMm,"postRadiusMm"),postHeightMm:finitePositive(args.postHeightMm,"postHeightMm"),insetMm:finitePositive(args.insetMm,"insetMm")};if(parsed.insetMm+parsed.postRadiusMm>=parsed.widthMm/2||parsed.insetMm+parsed.postRadiusMm>=parsed.depthMm/2)throw new Error("insetMm leaves insufficient room for the mounting posts.");return parsed;}
export function parseCreateEnclosureArgs(args:Record<string,unknown>):CreateEnclosureArgs{const parsed={widthMm:finitePositive(args.widthMm,"widthMm"),depthMm:finitePositive(args.depthMm,"depthMm"),baseHeightMm:finitePositive(args.baseHeightMm,"baseHeightMm"),wallHeightMm:finitePositive(args.wallHeightMm,"wallHeightMm"),wallThicknessMm:finitePositive(args.wallThicknessMm,"wallThicknessMm")};if(parsed.wallThicknessMm*2>=parsed.widthMm||parsed.wallThicknessMm*2>=parsed.depthMm)throw new Error("wallThicknessMm leaves no usable interior space.");return parsed;}
function createDesignPreamble(){return `import adsk.core, adsk.fusion\napp = adsk.core.Application.get()\nif not app: raise RuntimeError("Fusion application unavailable")\nproduct = app.activeProduct\ndesign = adsk.fusion.Design.cast(product)\nif not design: raise RuntimeError("Active product is not a Fusion Design")\nroot = design.rootComponent\nexistingBodyCount = root.bRepBodies.count\n`;}
function verificationScript(operation:string,expectedNewBodies:number){return `\nbodyCount = root.bRepBodies.count\nnewBodyCount = bodyCount - existingBodyCount\nif newBodyCount != ${expectedNewBodies}: raise RuntimeError("Expected ${expectedNewBodies} newly created solid bodies, got " + str(newBodyCount))\nnewBodies = [root.bRepBodies.item(i) for i in range(existingBodyCount, bodyCount)]\nminX = minY = minZ = 1e100\nmaxX = maxY = maxZ = -1e100\nfor b in newBodies:\n    box = b.boundingBox\n    minX = min(minX, box.minPoint.x); minY = min(minY, box.minPoint.y); minZ = min(minZ, box.minPoint.z)\n    maxX = max(maxX, box.maxPoint.x); maxY = max(maxY, box.maxPoint.y); maxZ = max(maxZ, box.maxPoint.z)\nprint("AI_FACTORY_CAD_RESULT")\nprint("operation=${operation}")\nprint("bodies=" + str(newBodyCount))\nprint("width_mm=" + str((maxX-minX)*10.0))\nprint("depth_mm=" + str((maxY-minY)*10.0))\nprint("height_mm=" + str((maxZ-minZ)*10.0))\nprint("document=" + app.activeDocument.name)\n`;}
export function createBoxScript({widthMm,depthMm,heightMm}:CreateBoxArgs){const w=widthMm/10,d=depthMm/10,h=heightMm/10;return `${createDesignPreamble()}sketch = root.sketches.add(root.xYConstructionPlane)\nsketch.sketchCurves.sketchLines.addTwoPointRectangle(adsk.core.Point3D.create(0,0,0),adsk.core.Point3D.create(${w},${d},0))\ninput = root.features.extrudeFeatures.createInput(sketch.profiles.item(0),adsk.fusion.FeatureOperations.NewBodyFeatureOperation)\ninput.setDistanceExtent(False,adsk.core.ValueInput.createByReal(${h}))\nresult = root.features.extrudeFeatures.add(input)\nif not result: raise RuntimeError("Box extrusion failed")\n${verificationScript("create_box",1)}`;}
export function createCylinderScript({radiusMm,heightMm}:CreateCylinderArgs){const r=radiusMm/10,h=heightMm/10;return `${createDesignPreamble()}sketch = root.sketches.add(root.xYConstructionPlane)\nsketch.sketchCurves.sketchCircles.addByCenterRadius(adsk.core.Point3D.create(0,0,0),${r})\ninput = root.features.extrudeFeatures.createInput(sketch.profiles.item(0),adsk.fusion.FeatureOperations.NewBodyFeatureOperation)\ninput.setDistanceExtent(False,adsk.core.ValueInput.createByReal(${h}))\nresult = root.features.extrudeFeatures.add(input)\nif not result: raise RuntimeError("Cylinder extrusion failed")\n${verificationScript("create_cylinder",1)}print("radius_mm=${radiusMm}")`;}
export function createMountingPlateScript({widthMm,depthMm,plateHeightMm,postRadiusMm,postHeightMm,insetMm}:CreateMountingPlateArgs){const w=widthMm/10,d=depthMm/10,ph=plateHeightMm/10,r=postRadiusMm/10,hh=postHeightMm/10,i=insetMm/10;const pts=[[i,i],[w-i,i],[i,d-i],[w-i,d-i]];let s=`${createDesignPreamble()}extrudes = root.features.extrudeFeatures\nplateSketch = root.sketches.add(root.xYConstructionPlane)\nplateSketch.sketchCurves.sketchLines.addTwoPointRectangle(adsk.core.Point3D.create(0,0,0),adsk.core.Point3D.create(${w},${d},0))\nplateInput = extrudes.createInput(plateSketch.profiles.item(0),adsk.fusion.FeatureOperations.NewBodyFeatureOperation)\nplateInput.setDistanceExtent(False,adsk.core.ValueInput.createByReal(${ph}))\nplate = extrudes.add(plateInput)\nif not plate: raise RuntimeError("Plate extrusion failed")\n`;pts.forEach(([x,y],n)=>{s+=`postSketch${n} = root.sketches.add(root.xYConstructionPlane)\npostSketch${n}.sketchCurves.sketchCircles.addByCenterRadius(adsk.core.Point3D.create(${x},${y},0),${r})\npostInput${n} = extrudes.createInput(postSketch${n}.profiles.item(0),adsk.fusion.FeatureOperations.NewBodyFeatureOperation)\npostInput${n}.setDistanceExtent(False,adsk.core.ValueInput.createByReal(${hh}))\npost${n} = extrudes.add(postInput${n})\nif not post${n}: raise RuntimeError("Mounting post failed")\n`});return s+verificationScript("create_mounting_plate",5);}
export function createEnclosureScript({widthMm,depthMm,baseHeightMm,wallHeightMm,wallThicknessMm}:CreateEnclosureArgs){const w=widthMm/10,d=depthMm/10,b=baseHeightMm/10,total=(baseHeightMm+wallHeightMm)/10,t=wallThicknessMm/10;const rects=[[0,0,w,d,b],[0,0,w,t,total],[0,d-t,w,d,total],[0,t,t,d-t,total],[w-t,t,w,d-t,total]];let s=createDesignPreamble()+"extrudes = root.features.extrudeFeatures\n";rects.forEach(([x1,y1,x2,y2,h],n)=>{s+=`sketch${n} = root.sketches.add(root.xYConstructionPlane)\nsketch${n}.sketchCurves.sketchLines.addTwoPointRectangle(adsk.core.Point3D.create(${x1},${y1},0),adsk.core.Point3D.create(${x2},${y2},0))\ninput${n} = extrudes.createInput(sketch${n}.profiles.item(0),adsk.fusion.FeatureOperations.NewBodyFeatureOperation)\ninput${n}.setDistanceExtent(False,adsk.core.ValueInput.createByReal(${h}))\nbody${n} = extrudes.add(input${n})\nif not body${n}: raise RuntimeError("Enclosure extrusion failed")\n`});return s+verificationScript("create_enclosure",5);}
function parseToolText(result:unknown,operation:CadResult["operation"],expected?:{width:number;depth:number;height:number}){const text=typeof result==="string"?result:JSON.stringify(result);const body=text.match(/bodies=(\d+)/)?.[1],width=text.match(/width_mm=([0-9.eE+-]+)/)?.[1],depth=text.match(/depth_mm=([0-9.eE+-]+)/)?.[1],height=text.match(/height_mm=([0-9.eE+-]+)/)?.[1],radius=text.match(/radius_mm=([0-9.eE+-]+)/)?.[1],document=text.match(/document=([^\r\n]+)/)?.[1]?.trim();if(!width||!depth||!height)return{success:false,operation,error:`Fusion did not return verification dimensions: ${text}`};const dimensionsMm={width:Number(width),depth:Number(depth),height:Number(height)};if(expected){const tolerance=0.05;const mismatch=["width","depth","height"].find(key=>Math.abs(dimensionsMm[key as keyof typeof dimensionsMm]-expected[key as keyof typeof expected])>tolerance);if(mismatch)return{success:false,operation,dimensionsMm,error:`Verified ${mismatch} ${dimensionsMm[mismatch as keyof typeof dimensionsMm]} mm does not match requested ${expected[mismatch as keyof typeof expected]} mm.`};}return{success:true,operation,bodies:body?Number(body):undefined,dimensionsMm,radiusMm:radius?Number(radius):undefined,document};}
async function executeScript(script:string,operation:CadResult["operation"],expected?:{width:number;depth:number;height:number}){if(!fusion.isConnected())await fusion.connect();const result=await withTimeout(fusion.callTool("fusion_mcp_execute",{featureType:"script",object:{script}}),config.TOOL_TIMEOUT_MS,`Fusion ${operation}`);return parseToolText(result,operation,expected);}
export async function executeCreateBox(args:Record<string,unknown>){const parsed=parseCreateBoxArgs(args);return executeScript(createBoxScript(parsed),"create_box",{width:parsed.widthMm,depth:parsed.depthMm,height:parsed.heightMm});}
export async function executeCreateCylinder(args:Record<string,unknown>){const parsed=parseCreateCylinderArgs(args);return executeScript(createCylinderScript(parsed),"create_cylinder",{width:parsed.radiusMm*2,depth:parsed.radiusMm*2,height:parsed.heightMm});}
export async function executeCreateMountingPlate(args:Record<string,unknown>){const parsed=parseCreateMountingPlateArgs(args);return executeScript(createMountingPlateScript(parsed),"create_mounting_plate",{width:parsed.widthMm,depth:parsed.depthMm,height:Math.max(parsed.plateHeightMm,parsed.postHeightMm)});}
export async function executeCreateEnclosure(args:Record<string,unknown>){const parsed=parseCreateEnclosureArgs(args);return executeScript(createEnclosureScript(parsed),"create_enclosure",{width:parsed.widthMm,depth:parsed.depthMm,height:parsed.baseHeightMm+parsed.wallHeightMm});}
