import OpenAI from "openai";
import { executeCreateBox,executeCreateCylinder,executeCreateMountingPlate,executeCreateEnclosure } from "./cad.js";
import { executeCreatePlate } from "./plate.js";
import { createParametricBox } from "./parametric.js";
import { exploreDesignSpace } from "./design-space.js";
import { buildRequirementsDrivenElectronicsArchitecture } from "./electronics.js";
import { validateRobotDesign, robotDesignHash } from "./robot-design.js";
import { compileRobotDesignToFusion } from "./robot-cad-compiler.js";
import { validateKiCadDesign } from "./kicad.js";
import { selectElectronicsComponents } from "./electronics-selection.js";
import { analyzeElectronicsEngineering } from "./electronics-analysis.js";
import { generateFirmwareProject } from "./firmware.js";
import { planFirmwareFlash, runFirmwareHil } from "./firmware-io.js";
import { listComponents } from "./knowledge.js";
import { fusion } from "./fusion.js";
import { evaluateFusionOperation } from "./policy.js";
export type CapabilityDomain="cad"|"electronics"|"mechanics"|"simulation"|"software"|"testing"|"manufacturing";
export type Capability={name:string;domain:CapabilityDomain;description:string;parameters:Record<string,unknown>;execute:(args:Record<string,unknown>)=>Promise<unknown>;requiresFusion?:boolean;discoverable?:boolean};
const number={type:"number"};const string={type:"string"};const object=(properties:Record<string,unknown>,required:string[])=>({type:"object",properties,required,additionalProperties:false}); const jsonObject={type:"object",additionalProperties:true};
export const capabilities:Capability[]=[
{name:"ai_factory_create_box",domain:"cad",description:"Legacy CAD primitive. Internal compatibility capability; model-facing design should use ai_factory_submit_robot_design.",parameters:object({widthMm:number,depthMm:number,heightMm:number},["widthMm","depthMm","heightMm"]),execute:executeCreateBox,requiresFusion:true,discoverable:false},
{name:"ai_factory_create_cylinder",domain:"cad",description:"Legacy CAD primitive. Internal compatibility capability; model-facing design should use ai_factory_submit_robot_design.",parameters:object({radiusMm:number,heightMm:number},["radiusMm","heightMm"]),execute:executeCreateCylinder,requiresFusion:true,discoverable:false},
{name:"ai_factory_create_plate",domain:"cad",description:"Legacy CAD primitive. Internal compatibility capability; model-facing design should use ai_factory_submit_robot_design.",parameters:object({widthMm:number,depthMm:number,heightMm:number,holeDiameterMm:number,holeXmm:number,holeYmm:number},["widthMm","depthMm","heightMm","holeDiameterMm"]),execute:executeCreatePlate,requiresFusion:true,discoverable:false},
{name:"ai_factory_create_mounting_plate",domain:"cad",description:"Legacy CAD primitive. Internal compatibility capability; model-facing design should use ai_factory_submit_robot_design.",parameters:object({widthMm:number,depthMm:number,plateHeightMm:number,postRadiusMm:number,postHeightMm:number,insetMm:number},["widthMm","depthMm","plateHeightMm","postRadiusMm","postHeightMm","insetMm"]),execute:executeCreateMountingPlate,requiresFusion:true,discoverable:false},
{name:"ai_factory_create_enclosure",domain:"cad",description:"Legacy CAD primitive. Internal compatibility capability; model-facing design should use ai_factory_submit_robot_design.",parameters:object({widthMm:number,depthMm:number,baseHeightMm:number,wallHeightMm:number,wallThicknessMm:number},["widthMm","depthMm","baseHeightMm","wallHeightMm","wallThicknessMm"]),execute:executeCreateEnclosure,requiresFusion:true,discoverable:false},
{name:"ai_factory_inspect_fusion",domain:"cad",description:"Inspect Fusion document state. Use queryType=document for document inspection: recent lists recent documents, search finds documents by name using name, and open lists currently open documents. queryType=screenshot returns a view image. queryType=apiDocumentation searches the live Fusion API documentation. Do not repeat an identical failed inspection call.",parameters:object({queryType:{type:"string",enum:["document","projects","apiDocumentation","screenshot","activeCommand"]},operation:{type:"string",enum:["search","open","recent"]},name:string,project:string,searchPattern:string,filter:string,direction:{type:"string",enum:["current","front","back","top","bottom","left","right","iso-bottom-left","iso-bottom-right","iso-top-left","iso-top-right"]},width:{type:"number",minimum:32,maximum:4096},height:{type:"number",minimum:32,maximum:4096},apiCategory:{type:"string",enum:["class","member","description","all"]}},["queryType"]),execute:async(args)=>{const queryType=String(args.queryType);const forwarded:Record<string,unknown>={queryType};if(queryType==="document"){const operation=String(args.operation??"recent");if(!["search","open","recent"].includes(operation))throw new Error("Unsupported Fusion document inspection operation.");forwarded.operation=operation;if(operation==="search"){const name=typeof args.name==="string"?args.name.trim():"";if(!name)throw new Error("Fusion document search requires name.");forwarded.name=name;if(typeof args.project==="string"&&args.project.trim())forwarded.project=args.project.trim();}}else if(queryType==="apiDocumentation"){const searchPattern=typeof args.searchPattern==="string"?args.searchPattern.trim():"";if(!searchPattern)throw new Error("Fusion API documentation search requires searchPattern.");forwarded.searchPattern=searchPattern;if(typeof args.filter==="string"&&args.filter.trim())forwarded.filter=args.filter.trim();if(typeof args.apiCategory==="string")forwarded.apiCategory=args.apiCategory;}else if(queryType==="screenshot"){if(typeof args.direction==="string")forwarded.direction=args.direction;if(typeof args.width==="number")forwarded.width=args.width;if(typeof args.height==="number")forwarded.height=args.height;}return fusion.callTool("fusion_mcp_read",forwarded);},requiresFusion:true},
{name:"ai_factory_explore_design_space",domain:"mechanics",description:"Deterministically enumerate, constrain, and rank a bounded parametric mechanical design space. This is analysis only: it does not modify CAD or approve a design. The best candidate is only best under the supplied variables, constraints, and objective.",parameters:object({model:jsonObject,designSpace:jsonObject,resultLimit:{type:"number",minimum:1,maximum:1000}},["model","designSpace"]),execute:async(args)=>{const candidates=exploreDesignSpace(args.model,args.designSpace);const limit=Math.max(1,Math.min(1000,Number(args.resultLimit??25)));return{schema:"ai-factory.design-space-result/v1",candidateCount:candidates.length,candidates:candidates.slice(0,limit),bestCandidate:candidates[0]??null};}},
{name:"ai_factory_plan_parametric_box",domain:"mechanics",description:"Legacy parametric primitive. Internal compatibility capability; model-facing design should use ai_factory_submit_robot_design.",parameters:object({name:string,widthMm:number,depthMm:number,heightMm:number},["name","widthMm","depthMm","heightMm"]),execute:async(args)=>createParametricBox(String(args.name),Number(args.widthMm),Number(args.depthMm),Number(args.heightMm)),discoverable:false},
{name:"ai_factory_submit_robot_design",domain:"mechanics",description:"Validate a complete model-authored robot design and immediately hand the validated design to the real Fusion CAD compiler. The model supplies the mission, requirements, arbitrary part topology, joints, and a vendor-neutral geometry operation graph. No robot template or prebuilt structure is selected for the model. The returned CAD result is authoritative evidence: success means Fusion accepted the generated CAD script; failure contains compiler evidence for revision. Unsupported geometry is never silently substituted.",parameters:object({design:jsonObject},["design"]),execute:async(args)=>{const design=validateRobotDesign(args.design);const designHash=robotDesignHash(design);const cad=await compileRobotDesignToFusion(design);return{schema:"ai-factory.robot-design-result/v1",design,designHash,cad};}},
{name:"ai_factory_compile_robot_cad",domain:"cad",description:"Compile a validated model-authored robot design into real Fusion CAD. The model supplies the geometry graph; this capability is the compiler/executor, not a robot template. Unsupported geometry is rejected rather than silently substituted with a primitive.",parameters:object({design:jsonObject},["design"]),execute:async(args)=>compileRobotDesignToFusion(args.design),requiresFusion:true},
{name:"ai_factory_design_electronics_architecture",domain:"electronics",description:"Build a deterministic requirements-driven electronics architecture skeleton from explicit electrical requirements. This is design analysis only: it does not select components, create a schematic, or authorize hardware.",parameters:object({requirements:{type:"array",minItems:1,items:{type:"object",additionalProperties:true}},name:string},["requirements"]),execute:async(args)=>buildRequirementsDrivenElectronicsArchitecture(args.requirements,args.name===undefined?undefined:String(args.name))},
{name:"ai_factory_validate_kicad_electronics",domain:"electronics",description:"Run the real KiCad CLI against project-scoped .kicad_sch and/or .kicad_pcb files. Produces ERC/DRC reports and optionally a schematic netlist. Paths are relative to the configured KiCad workspace; no arbitrary shell commands or filesystem paths are exposed.",parameters:object({schematicPath:string,pcbPath:string,exportNetlist:{type:"boolean"}},[]),execute:async(args)=>validateKiCadDesign({schematicPath:typeof args.schematicPath==="string"?args.schematicPath:undefined,pcbPath:typeof args.pcbPath==="string"?args.pcbPath:undefined,exportNetlist:args.exportNetlist===true})},
{name:"ai_factory_select_electronics_components",domain:"electronics",description:"Select project components against a requirements-driven electronics architecture and run deterministic electrical rule checks. Applies lifecycle, voltage-range, current-capacity, functional-block coverage, interface coverage, and uniqueness rules. Unknown ratings are not accepted as verified selection. This does not approve procurement or hardware use.",parameters:object({projectId:string,architecture:jsonObject,resultLimit:{type:"number",minimum:1,maximum:100}},["projectId","architecture"]),execute:async(args)=>selectElectronicsComponents(args.architecture,listComponents(String(args.projectId)),Number(args.resultLimit??20))},
{name:"ai_factory_analyze_electronics_engineering",domain:"electronics",description:"Analyze a verified electronics architecture and component selection for deterministic power-budget, thermal, signal-integrity, and interface risks. Unknown engineering data produces explicit findings and prevents a passing analysis; this is analysis only and does not authorize hardware.",parameters:object({architecture:jsonObject,selection:jsonObject},["architecture","selection"]),execute:async(args)=>analyzeElectronicsEngineering(args.architecture,args.selection)},
{name:"ai_factory_generate_firmware",domain:"software",description:"Generate a deterministic, architecture-lineage-aware portable C++ firmware project from a validated electronics architecture. The generated project is host-verifiable and does not authorize physical flashing; board-specific HAL/toolchain integration is required before hardware deployment.",parameters:object({architecture:jsonObject,target:jsonObject},["architecture","target"]),execute:async(args)=>generateFirmwareProject(args.architecture,args.target)},
{name:"ai_factory_run_firmware_hil",domain:"testing",description:"Build and execute a generated portable firmware project through the host HIL interface and parse structured heartbeat telemetry. This validates firmware behavior at the host boundary; it is not a substitute for physical hardware-in-the-loop testing.",parameters:object({project:jsonObject},["project"]),execute:async(args)=>runFirmwareHil(args.project)},
{name:"ai_factory_plan_firmware_flash",domain:"testing",description:"Build a constrained flash command plan for supported hardware tools without executing physical hardware writes. Physical execution requires a dedicated authorized hardware adapter.",parameters:object({tool:{type:"string",enum:["avrdude","dfu-util","openocd"]},artifactPath:string,device:string,execute:{type:"boolean"}},["tool","artifactPath","device"]),execute:async(args)=>planFirmwareFlash(args)}
];
export const getCapability=(name:string)=>capabilities.find(c=>c.name===name);export const listCapabilities=(domain?:CapabilityDomain)=>capabilities.filter(c=>(c.discoverable!==false)&&(domain?c.domain===domain:true));
export const toOpenAITools=(options:{fusionAvailable?:boolean}={}):OpenAI.Chat.Completions.ChatCompletionTool[]=>capabilities.filter(c=>c.discoverable!==false&&(options.fusionAvailable!==false||!c.requiresFusion)).map(c=>({type:"function" as const,function:{name:c.name,description:c.description,parameters:c.parameters}}));
export async function executeCapability(name:string,args:Record<string,unknown>){const capability=getCapability(name);if(!capability)throw new Error(`Unknown factory capability: ${name}`);const policy=evaluateFusionOperation(name,args);if(!policy.allowed)throw new Error(`Operation denied by policy: ${policy.reason}`);if(policy.requiresApproval)throw new Error(`Operation requires explicit human approval: ${policy.reason}`);if(capability.requiresFusion&&!fusion.isConnected())throw new Error("Fusion MCP is unavailable; CAD capability cannot execute.");return capability.execute(args);}
