import OpenAI from "openai";
import { executeCreateBox,executeCreateCylinder,executeCreateMountingPlate,executeCreateEnclosure } from "./cad.js";
import { executeCreatePlate } from "./plate.js";
import { createParametricBox } from "./parametric.js";
import { fusion } from "./fusion.js";
import { evaluateFusionOperation } from "./policy.js";
export type CapabilityDomain="cad"|"electronics"|"mechanics"|"simulation"|"software"|"testing"|"manufacturing";
export type Capability={name:string;domain:CapabilityDomain;description:string;parameters:Record<string,unknown>;execute:(args:Record<string,unknown>)=>Promise<unknown>;requiresFusion?:boolean;discoverable?:boolean};
const number={type:"number"};const object=(properties:Record<string,unknown>,required:string[])=>({type:"object",properties,required,additionalProperties:false});
export const capabilities:Capability[]=[
{name:"ai_factory_create_box",domain:"cad",description:"Create and verify a rectangular solid in the active Fusion design.",parameters:object({widthMm:number,depthMm:number,heightMm:number},["widthMm","depthMm","heightMm"]),execute:executeCreateBox,requiresFusion:true},
{name:"ai_factory_create_cylinder",domain:"cad",description:"Create and verify a cylindrical solid in the active Fusion design.",parameters:object({radiusMm:number,heightMm:number},["radiusMm","heightMm"]),execute:executeCreateCylinder,requiresFusion:true},
{name:"ai_factory_create_plate",domain:"cad",description:"Create and verify a rectangular plate with a through-hole in the active Fusion design.",parameters:object({widthMm:number,depthMm:number,heightMm:number,holeDiameterMm:number,holeXmm:number,holeYmm:number},["widthMm","depthMm","heightMm","holeDiameterMm"]),execute:executeCreatePlate,requiresFusion:true},
{name:"ai_factory_create_mounting_plate",domain:"cad",description:"Create and verify a rectangular mounting plate with four posts in the active Fusion design.",parameters:object({widthMm:number,depthMm:number,plateHeightMm:number,postRadiusMm:number,postHeightMm:number,insetMm:number},["widthMm","depthMm","plateHeightMm","postRadiusMm","postHeightMm","insetMm"]),execute:executeCreateMountingPlate,requiresFusion:true},
{name:"ai_factory_create_enclosure",domain:"cad",description:"Create and verify an open-top electronics enclosure in the active Fusion design.",parameters:object({widthMm:number,depthMm:number,baseHeightMm:number,wallHeightMm:number,wallThicknessMm:number},["widthMm","depthMm","baseHeightMm","wallHeightMm","wallThicknessMm"]),execute:executeCreateEnclosure,requiresFusion:true},
{name:"ai_factory_inspect_fusion",domain:"cad",description:"Inspect the currently open Fusion documents using the Fusion MCP document read surface. Use this only when existing CAD state is relevant.",parameters:object({queryType:{type:"string",enum:["document"]}},["queryType"]),execute:async(args)=>{const queryType=String(args.queryType);if(queryType!=="document")throw new Error("Unsupported Fusion inspection query type.");return fusion.callTool("fusion_mcp_read",{queryType});},requiresFusion:true},
{name:"ai_factory_plan_parametric_box",domain:"mechanics",description:"Create a vendor-neutral, validated parametric mechanical box definition without executing CAD or manufacturing.",parameters:object({name:{type:"string"},widthMm:number,depthMm:number,heightMm:number},["name","widthMm","depthMm","heightMm"]),execute:async(args)=>createParametricBox(String(args.name),Number(args.widthMm),Number(args.depthMm),Number(args.heightMm))}
];
export const getCapability=(name:string)=>capabilities.find(c=>c.name===name);export const listCapabilities=(domain?:CapabilityDomain)=>capabilities.filter(c=>(c.discoverable!==false)&&(domain?c.domain===domain:true));
export const toOpenAITools=(options:{fusionAvailable?:boolean}={}):OpenAI.Chat.Completions.ChatCompletionTool[]=>capabilities.filter(c=>(options.fusionAvailable!==false||!c.requiresFusion)).map(c=>({type:"function" as const,function:{name:c.name,description:c.description,parameters:c.parameters}}));
export async function executeCapability(name:string,args:Record<string,unknown>){const capability=getCapability(name);if(!capability)throw new Error(`Unknown factory capability: ${name}`);const policy=evaluateFusionOperation(name,args);if(!policy.allowed)throw new Error(`Operation denied by policy: ${policy.reason}`);if(policy.requiresApproval)throw new Error(`Operation requires explicit human approval: ${policy.reason}`);if(capability.requiresFusion&&!fusion.isConnected())throw new Error("Fusion MCP is unavailable; CAD capability cannot execute.");return capability.execute(args);}
