import OpenAI from "openai";
import { executeCreateBox,executeCreateCylinder,executeCreateMountingPlate,executeCreateEnclosure } from "./cad.js";
import { executeCreatePlate } from "./plate.js";
import { createParametricBox } from "./parametric.js";
import { exploreDesignSpace } from "./design-space.js";
import { buildRequirementsDrivenElectronicsArchitecture } from "./electronics.js";
import { fusion } from "./fusion.js";
import { evaluateFusionOperation } from "./policy.js";
export type CapabilityDomain="cad"|"electronics"|"mechanics"|"simulation"|"software"|"testing"|"manufacturing";
export type Capability={name:string;domain:CapabilityDomain;description:string;parameters:Record<string,unknown>;execute:(args:Record<string,unknown>)=>Promise<unknown>;requiresFusion?:boolean;discoverable?:boolean};
const number={type:"number"};const string={type:"string"};const object=(properties:Record<string,unknown>,required:string[])=>({type:"object",properties,required,additionalProperties:false});
const jsonObject={type:"object",additionalProperties:true};
export const capabilities:Capability[]=[
{name:"ai_factory_create_box",domain:"cad",description:"Create and verify a rectangular solid in the active Fusion design.",parameters:object({widthMm:number,depthMm:number,heightMm:number},["widthMm","depthMm","heightMm"]),execute:executeCreateBox,requiresFusion:true},
{name:"ai_factory_create_cylinder",domain:"cad",description:"Create and verify a cylindrical solid in the active Fusion design.",parameters:object({radiusMm:number,heightMm:number},["radiusMm","heightMm"]),execute:executeCreateCylinder,requiresFusion:true},
{name:"ai_factory_create_plate",domain:"cad",description:"Create and verify a rectangular plate with a through-hole in the active Fusion design. Hole coordinates are measured from the plate origin; omit them for the centered hole.",parameters:object({widthMm:number,depthMm:number,heightMm:number,holeDiameterMm:number,holeXmm:number,holeYmm:number},["widthMm","depthMm","heightMm","holeDiameterMm"]),execute:executeCreatePlate,requiresFusion:true},
{name:"ai_factory_create_mounting_plate",domain:"cad",description:"Create and verify a rectangular mounting plate with four posts in the active Fusion design.",parameters:object({widthMm:number,depthMm:number,plateHeightMm:number,postRadiusMm:number,postHeightMm:number,insetMm:number},["widthMm","depthMm","plateHeightMm","postRadiusMm","postHeightMm","insetMm"]),execute:executeCreateMountingPlate,requiresFusion:true},
{name:"ai_factory_create_enclosure",domain:"cad",description:"Create and verify an open-top electronics enclosure in the active Fusion design.",parameters:object({widthMm:number,depthMm:number,baseHeightMm:number,wallHeightMm:number,wallThicknessMm:number},["widthMm","depthMm","baseHeightMm","wallHeightMm","wallThicknessMm"]),execute:executeCreateEnclosure,requiresFusion:true},
{name:"ai_factory_inspect_fusion",domain:"cad",description:"Inspect the currently open Fusion document through the Fusion MCP document read surface. The operation must be explicit. Use recent to inspect recent documents, search to search documents, or open to open a known document. Do not call this repeatedly after an error.",parameters:object({operation:{type:"string",enum:["search","open","recent"]},query:string,id:string},["operation"]),execute:async(args)=>{const operation=String(args.operation);if(!["search","open","recent"].includes(operation))throw new Error("Unsupported Fusion document inspection operation.");const forwarded:Record<string,unknown>={entity:"document",operation};if(typeof args.query==="string"&&args.query.trim())forwarded.query=args.query;if(typeof args.id==="string"&&args.id.trim())forwarded.id=args.id;return fusion.callTool("fusion_mcp_read",forwarded);},requiresFusion:true},
{name:"ai_factory_explore_design_space",domain:"mechanics",description:"Deterministically enumerate, constrain, and rank a bounded parametric mechanical design space. This is analysis only: it does not modify CAD or approve a design. The best candidate is only best under the supplied variables, constraints, and objective.",parameters:object({model:jsonObject,designSpace:jsonObject,resultLimit:{type:"number",minimum:1,maximum:1000}},["model","designSpace"]),execute:async(args)=>{const candidates=exploreDesignSpace(args.model,args.designSpace);const limit=Math.max(1,Math.min(1000,Number(args.resultLimit??25)));return{schema:"ai-factory.design-space-result/v1",candidateCount:candidates.length,candidates:candidates.slice(0,limit),bestCandidate:candidates[0]??null};}},
{name:"ai_factory_plan_parametric_box",domain:"mechanics",description:"Create a vendor-neutral, validated parametric mechanical box definition without executing CAD or manufacturing.",parameters:object({name:string,widthMm:number,depthMm:number,heightMm:number},["name","widthMm","depthMm","heightMm"]),execute:async(args)=>createParametricBox(String(args.name),Number(args.widthMm),Number(args.depthMm),Number(args.heightMm))},
{name:"ai_factory_design_electronics_architecture",domain:"electronics",description:"Build a deterministic requirements-driven electronics architecture skeleton from explicit electrical requirements. This is design analysis only: it does not select components, create a schematic, or authorize hardware.",parameters:object({requirements:{type:"array",minItems:1,items:{type:"object",additionalProperties:true}},name:string},["requirements"]),execute:async(args)=>buildRequirementsDrivenElectronicsArchitecture(args.requirements,args.name===undefined?undefined:String(args.name))}
];
export const getCapability=(name:string)=>capabilities.find(c=>c.name===name);export const listCapabilities=(domain?:CapabilityDomain)=>capabilities.filter(c=>(c.discoverable!==false)&&(domain?c.domain===domain:true));
export const toOpenAITools=(options:{fusionAvailable?:boolean}={}):OpenAI.Chat.Completions.ChatCompletionTool[]=>capabilities.filter(c=>(options.fusionAvailable!==false||!c.requiresFusion)).map(c=>({type:"function" as const,function:{name:c.name,description:c.description,parameters:c.parameters}}));
export async function executeCapability(name:string,args:Record<string,unknown>){const capability=getCapability(name);if(!capability)throw new Error(`Unknown factory capability: ${name}`);const policy=evaluateFusionOperation(name,args);if(!policy.allowed)throw new Error(`Operation denied by policy: ${policy.reason}`);if(policy.requiresApproval)throw new Error(`Operation requires explicit human approval: ${policy.reason}`);if(capability.requiresFusion&&!fusion.isConnected())throw new Error("Fusion MCP is unavailable; CAD capability cannot execute.");return capability.execute(args);}
