import { db } from "./db.js";
import { randomUUID } from "node:crypto";
import type { Requirement, EngineeringPlan } from "./engineering.js";

export type EngineeringFactKind = "decision"|"assumption"|"constraint"|"acceptance_criterion";

export function saveRequirements(projectId:string, requirements:Requirement[]) {
  const now=new Date().toISOString();
  const insert=db.prepare(`INSERT INTO engineering_requirements (id,project_id,description,category,value,unit,priority,verification_method,verification_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET description=excluded.description,category=excluded.category,value=excluded.value,unit=excluded.unit,priority=excluded.priority,verification_method=excluded.verification_method,verification_status=excluded.verification_status,updated_at=excluded.updated_at`);
  const revision=db.prepare(`INSERT INTO requirement_revisions (id,requirement_id,project_id,version,description,category,value,unit,priority,verification_method,verification_status,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM requirement_revisions WHERE requirement_id=? AND version=?)`);
  const latest=db.prepare(`SELECT COALESCE(MAX(version),0) AS version FROM requirement_revisions WHERE requirement_id=?`);
  const tx=db.transaction(()=>{for(const r of requirements){const value=r.value===undefined?null:String(r.value);insert.run(r.id,projectId,r.description,r.category,value,r.unit??null,r.priority,r.verificationMethod??null,r.verificationStatus,now,now);const next=(latest.get(r.id) as {version:number}).version+1;revision.run(`REV-${r.id}-${next}`,r.id,projectId,next,r.description,r.category,value,r.unit??null,r.priority,r.verificationMethod??null,r.verificationStatus,now,r.id,next);}});tx();
}
export function listRequirements(projectId:string){return db.prepare(`SELECT * FROM engineering_requirements WHERE project_id=? ORDER BY created_at`).all(projectId);}
export function listRequirementRevisions(projectId:string,requirementId?:string){return requirementId?db.prepare(`SELECT * FROM requirement_revisions WHERE project_id=? AND requirement_id=? ORDER BY version ASC`).all(projectId,requirementId):db.prepare(`SELECT * FROM requirement_revisions WHERE project_id=? ORDER BY requirement_id,version ASC`).all(projectId);}
export function recordEngineeringFact(projectId:string,kind:EngineeringFactKind,key:string,statement:string,value:unknown,supersedesId?:string){const latest=db.prepare(`SELECT COALESCE(MAX(version),0) AS version FROM engineering_facts WHERE project_id=? AND kind=? AND key=?`).get(projectId,kind,key) as {version:number};const version=latest.version+1;const id=randomUUID();const now=new Date().toISOString();const tx=db.transaction(()=>{if(supersedesId)db.prepare(`UPDATE engineering_facts SET status='superseded',updated_at=? WHERE id=?`).run(now,supersedesId);db.prepare(`INSERT INTO engineering_facts(id,project_id,kind,key,statement,value_json,version,status,supersedes_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,kind,key,statement,JSON.stringify(value),version,"active",supersedesId??null,now,now);});tx();return id;}
export function listEngineeringFacts(projectId:string,kind?:EngineeringFactKind){return kind?db.prepare(`SELECT * FROM engineering_facts WHERE project_id=? AND kind=? ORDER BY key,version ASC`).all(projectId,kind):db.prepare(`SELECT * FROM engineering_facts WHERE project_id=? ORDER BY kind,key,version ASC`).all(projectId);}
export function savePlan(projectId:string,plan:EngineeringPlan){const now=new Date().toISOString();db.prepare(`INSERT INTO engineering_plans (id,project_id,objective,plan_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET objective=excluded.objective,plan_json=excluded.plan_json,updated_at=excluded.updated_at`).run(plan.id,projectId,plan.objective,JSON.stringify(plan),"draft",now,now);}
export function getPlan(projectId:string){const row=db.prepare(`SELECT * FROM engineering_plans WHERE project_id=? ORDER BY updated_at DESC LIMIT 1`).get(projectId) as {plan_json:string}|undefined;return row?JSON.parse(row.plan_json) as EngineeringPlan:null;}
export function linkFusionProject(projectId:string,link:{hubId?:string;fusionProjectId?:string;designId?:string}){db.prepare(`INSERT INTO fusion_links(project_id,hub_id,fusion_project_id,design_id,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(project_id) DO UPDATE SET hub_id=excluded.hub_id,fusion_project_id=excluded.fusion_project_id,design_id=excluded.design_id,updated_at=excluded.updated_at`).run(projectId,link.hubId??null,link.fusionProjectId??null,link.designId??null,new Date().toISOString());}
export function getFusionLink(projectId:string){return db.prepare(`SELECT * FROM fusion_links WHERE project_id=?`).get(projectId);}
export function addVerificationRecord(input:{projectId:string;runId?:string;requirementId?:string;status:"pass"|"fail"|"blocked";evidence:unknown}){const id=randomUUID();db.prepare(`INSERT INTO verification_records (id,project_id,run_id,requirement_id,status,evidence,created_at) VALUES (?,?,?,?,?,?,?)`).run(id,input.projectId,input.runId??null,input.requirementId??null,input.status,JSON.stringify(input.evidence),new Date().toISOString());return id;}
export function listVerificationRecords(projectId:string){return db.prepare(`SELECT * FROM verification_records WHERE project_id=? ORDER BY created_at ASC`).all(projectId);}
