import { z } from "zod";
import { randomUUID } from "node:crypto";
import { db } from "./db.js";

export const EvidenceKind=z.enum(["manual","datasheet","standard","supplier","measurement","simulation","generated"]);
export const EvidenceSource=z.object({kind:EvidenceKind,ref:z.string().min(1),uri:z.string().url().optional(),observedAt:z.string().datetime().optional(),expiresAt:z.string().datetime().optional(),confidence:z.number().min(0).max(1).default(1),contentHash:z.string().optional(),metadata:z.record(z.unknown()).default({})});
export type EvidenceSourceInput=z.input<typeof EvidenceSource>;
export const EvidenceClaim=z.object({sourceId:z.string().min(1),claim:z.string().min(1),subject:z.string().optional(),property:z.string().optional(),value:z.unknown().optional(),status:z.enum(["active","superseded","disputed"]).default("active")});
export type EvidenceClaimInput=z.input<typeof EvidenceClaim>;
export function addEvidenceSource(projectId:string,input:EvidenceSourceInput){const value=EvidenceSource.parse(input),id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO evidence_sources(id,project_id,kind,ref,uri,observed_at,expires_at,confidence,content_hash,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,value.kind,value.ref,value.uri??null,value.observedAt??null,value.expiresAt??null,value.confidence,value.contentHash??null,JSON.stringify(value.metadata),now,now);return id;}
export function listEvidenceSources(projectId:string){return db.prepare(`SELECT * FROM evidence_sources WHERE project_id=? ORDER BY updated_at DESC`).all(projectId);}
export function getEvidenceSource(id:string){return db.prepare(`SELECT * FROM evidence_sources WHERE id=?`).get(id);}
export function addEvidenceClaim(projectId:string,input:EvidenceClaimInput){const value=EvidenceClaim.parse(input);const source=getEvidenceSource(value.sourceId) as {project_id:string}|undefined;if(!source||source.project_id!==projectId)throw new Error("evidence source not found in project");const id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO evidence_claims(id,project_id,source_id,claim,subject,property,value_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,value.sourceId,value.claim,value.subject??null,value.property??null,JSON.stringify(value.value??null),value.status,now,now);return id;}
export function listEvidenceClaims(projectId:string){return db.prepare(`SELECT c.*,s.kind source_kind,s.ref source_ref,s.uri source_uri,s.observed_at,s.expires_at,s.confidence,s.content_hash FROM evidence_claims c JOIN evidence_sources s ON s.id=c.source_id WHERE c.project_id=? ORDER BY c.updated_at DESC`).all(projectId);}
export function searchEvidence(projectId:string,query:string){const term=`%${query.trim()}%`;return db.prepare(`SELECT c.*,s.kind source_kind,s.ref source_ref,s.uri source_uri,s.observed_at,s.expires_at,s.confidence,s.content_hash,CASE WHEN s.expires_at IS NOT NULL AND s.expires_at < ? THEN 0 ELSE 1 END fresh FROM evidence_claims c JOIN evidence_sources s ON s.id=c.source_id WHERE c.project_id=? AND c.status='active' AND (c.claim LIKE ? OR COALESCE(c.subject,'') LIKE ? OR COALESCE(c.property,'') LIKE ?) ORDER BY fresh DESC,s.confidence DESC,c.updated_at DESC`).all(new Date().toISOString(),projectId,term,term,term);}
export function getEvidenceFreshness(projectId:string){const now=new Date().toISOString();return db.prepare(`SELECT COUNT(*) total, SUM(CASE WHEN expires_at IS NOT NULL AND expires_at < ? THEN 1 ELSE 0 END) expired, SUM(CASE WHEN expires_at IS NULL OR expires_at >= ? THEN 1 ELSE 0 END) current FROM evidence_sources WHERE project_id=?`).get(now,now,projectId);}
