import { z } from "zod";
import { randomUUID } from "node:crypto";
import { db } from "./db.js";

export const Unit = z.enum(["mm","cm","m","in","deg","rad","kg","g","N","Nm","V","A","W","Hz","s"]);
export type Unit=z.infer<typeof Unit>;
const LENGTH_TO_MM:Record<string,number>={mm:1,cm:10,m:1000,in:25.4};
export function convertUnit(value:number,from:Unit,to:Unit):number{if(from===to)return value;if(LENGTH_TO_MM[from]&&LENGTH_TO_MM[to])return value*LENGTH_TO_MM[from]/LENGTH_TO_MM[to];if(from==="deg"&&to==="rad")return value*Math.PI/180;if(from==="rad"&&to==="deg")return value*180/Math.PI;throw new Error(`unsupported unit conversion: ${from} -> ${to}`);}
export const KnowledgeSource=z.object({kind:z.enum(["manual","datasheet","standard","supplier","measurement","simulation","generated"]),ref:z.string().min(1),uri:z.string().url().optional(),observedAt:z.string().datetime().optional(),expiresAt:z.string().datetime().optional(),confidence:z.number().min(0).max(1).default(1)});
export const Material=z.object({name:z.string().min(1),grade:z.string().optional(),densityKgM3:z.number().positive().optional(),tensileStrengthMPa:z.number().positive().optional(),yieldStrengthMPa:z.number().positive().optional(),sources:z.array(KnowledgeSource).default([])});
export type MaterialInput=z.infer<typeof Material>;
export const Component=z.object({partNumber:z.string().min(1),name:z.string().min(1),manufacturer:z.string().optional(),category:z.string().min(1),lifecycle:z.enum(["active","nrnd","obsolete","unknown"]).default("unknown"),massG:z.number().nonnegative().optional(),voltageMinV:z.number().optional(),voltageMaxV:z.number().optional(),currentMaxA:z.number().nonnegative().optional(),sources:z.array(KnowledgeSource).default([])});
export type ComponentInput=z.infer<typeof Component>;
export const Standard=z.object({code:z.string().min(1),title:z.string().min(1),jurisdiction:z.string().optional(),revision:z.string().optional(),source:KnowledgeSource});
export const ManufacturingConstraint=z.object({process:z.string().min(1),material:z.string().optional(),minFeatureMm:z.number().positive().optional(),minWallMm:z.number().positive().optional(),toleranceMm:z.number().positive().optional(),maxPartMm:z.object({x:z.number().positive(),y:z.number().positive(),z:z.number().positive()}).optional(),source:KnowledgeSource});
export function addMaterial(projectId:string,input:MaterialInput){const value=Material.parse(input),id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO materials(id,project_id,name,grade,data_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).run(id,projectId,value.name,value.grade??null,JSON.stringify(value),now,now);return id;}
export function listMaterials(projectId:string){return db.prepare(`SELECT * FROM materials WHERE project_id=? ORDER BY name ASC,grade ASC`).all(projectId);}
export function addComponent(projectId:string,input:ComponentInput){const value=Component.parse(input),id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO components(id,project_id,part_number,name,manufacturer,category,lifecycle,data_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,value.partNumber,value.name,value.manufacturer??null,value.category,value.lifecycle,JSON.stringify(value),now,now);return id;}
export function listComponents(projectId:string){return db.prepare(`SELECT * FROM components WHERE project_id=? ORDER BY name ASC,part_number ASC`).all(projectId);}
export function addStandard(projectId:string,input:z.input<typeof Standard>){const value=Standard.parse(input),id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO standards(id,project_id,code,title,jurisdiction,revision,source_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,projectId,value.code,value.title,value.jurisdiction??null,value.revision??null,JSON.stringify(value.source),now,now);return id;}
export function listStandards(projectId:string){return db.prepare(`SELECT * FROM standards WHERE project_id=? ORDER BY code ASC`).all(projectId);}
export function addManufacturingConstraint(projectId:string,input:z.input<typeof ManufacturingConstraint>){const value=ManufacturingConstraint.parse(input),id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO manufacturing_constraints(id,project_id,process,material,data_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).run(id,projectId,value.process,value.material??null,JSON.stringify(value),now,now);return id;}
export function listManufacturingConstraints(projectId:string){return db.prepare(`SELECT * FROM manufacturing_constraints WHERE project_id=? ORDER BY process ASC`).all(projectId);}
export function listKnowledge(projectId:string){return{materials:listMaterials(projectId),components:listComponents(projectId),standards:listStandards(projectId),manufacturingConstraints:listManufacturingConstraints(projectId)};}

export const Supplier=z.object({name:z.string().min(1),code:z.string().min(1),website:z.string().url().optional(),country:z.string().optional(),status:z.enum(["active","inactive","unknown"]).default("unknown"),source:KnowledgeSource.optional()});
export type SupplierInput=z.input<typeof Supplier>;
export const SupplierOffer=z.object({componentId:z.string().min(1),supplierId:z.string().min(1),supplierPartNumber:z.string().min(1),unitPrice:z.number().nonnegative(),currency:z.string().regex(/^[A-Z]{3}$/),availability:z.enum(["in_stock","backorder","out_of_stock","unknown"]),stockQuantity:z.number().nonnegative().optional(),leadTimeDays:z.number().nonnegative().optional(),minimumOrderQuantity:z.number().positive().default(1),packQuantity:z.number().positive().default(1),source:KnowledgeSource,observedAt:z.string().datetime().optional(),expiresAt:z.string().datetime().optional()});
export type SupplierOfferInput=z.input<typeof SupplierOffer>;
export const ApprovedSource=z.object({componentId:z.string().min(1),supplierId:z.string().min(1),offerId:z.string().min(1).optional(),reason:z.string().min(1),approvedBy:z.string().min(1),validFrom:z.string().datetime().optional(),validUntil:z.string().datetime().optional(),status:z.enum(["approved","suspended","revoked"]).default("approved")});
export type ApprovedSourceInput=z.input<typeof ApprovedSource>;
function requireProjectEntity(table:string,id:string,projectId:string){const row=db.prepare(`SELECT id FROM ${table} WHERE id=? AND project_id=?`).get(id,projectId);if(!row)throw new Error(`${table} not found in project`);}
export function addSupplier(projectId:string,input:SupplierInput){const value=Supplier.parse(input),id=randomUUID(),now=new Date().toISOString();const statement=db.prepare(`INSERT INTO suppliers(id,project_id,code,name,website,country,status,source_json,created_at,updated_at) VALUES(@id,@projectId,@code,@name,@website,@country,@status,@sourceJson,@createdAt,@updatedAt)`);statement.run({id,projectId,code:value.code,name:value.name,website:value.website??null,country:value.country??null,status:value.status,sourceJson:JSON.stringify(value.source??null),createdAt:now,updatedAt:now});return id;}
export function listSuppliers(projectId:string){return db.prepare(`SELECT * FROM suppliers WHERE project_id=? ORDER BY name ASC,code ASC`).all(projectId);}
export function addSupplierOffer(projectId:string,input:SupplierOfferInput){const value=SupplierOffer.parse(input);requireProjectEntity("components",value.componentId,projectId);requireProjectEntity("suppliers",value.supplierId,projectId);const id=randomUUID(),now=new Date().toISOString();db.prepare(`INSERT INTO supplier_offers(id,project_id,component_id,supplier_id,supplier_part_number,unit_price,currency,availability,stock_quantity,lead_time_days,minimum_order_quantity,pack_quantity,source_json,observed_at,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,value.componentId,value.supplierId,value.supplierPartNumber,value.unitPrice,value.currency,value.availability,value.stockQuantity??null,value.leadTimeDays??null,value.minimumOrderQuantity,value.packQuantity,JSON.stringify(value.source),value.observedAt??null,value.expiresAt??null,now,now);return id;}
export function listSupplierOffers(projectId:string,componentId?:string){if(componentId){requireProjectEntity("components",componentId,projectId);return db.prepare(`SELECT o.*,s.name supplier_name,s.code supplier_code FROM supplier_offers o JOIN suppliers s ON s.id=o.supplier_id WHERE o.project_id=? AND o.component_id=? ORDER BY o.unit_price ASC,o.lead_time_days ASC`).all(projectId,componentId);}return db.prepare(`SELECT o.*,s.name supplier_name,s.code supplier_code FROM supplier_offers o JOIN suppliers s ON s.id=o.supplier_id WHERE o.project_id=? ORDER BY o.component_id,o.unit_price ASC`).all(projectId);}
export function addApprovedSource(projectId:string,input:ApprovedSourceInput){const value=ApprovedSource.parse(input);requireProjectEntity("components",value.componentId,projectId);requireProjectEntity("suppliers",value.supplierId,projectId);if(value.offerId){const offer=db.prepare(`SELECT id FROM supplier_offers WHERE id=? AND project_id=? AND component_id=? AND supplier_id=?`).get(value.offerId,projectId,value.componentId,value.supplierId);if(!offer)throw new Error("offer not found for component and supplier in project");}const id=randomUUID(),now=new Date().toISOString();const validUntil=value.validUntil??new Date(Date.now()+365*24*60*60*1000).toISOString();db.prepare(`INSERT INTO approved_sources(id,project_id,component_id,supplier_id,offer_id,reason,approved_by,valid_from,valid_until,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,value.componentId,value.supplierId,value.offerId??null,value.reason,value.approvedBy,value.validFrom??now,validUntil,value.status,now,now);return id;}
export function listApprovedSources(projectId:string,componentId?:string){if(componentId){requireProjectEntity("components",componentId,projectId);return db.prepare(`SELECT a.*,s.name supplier_name,s.code supplier_code FROM approved_sources a JOIN suppliers s ON s.id=a.supplier_id WHERE a.project_id=? AND a.component_id=? ORDER BY a.created_at DESC`).all(projectId,componentId);}return db.prepare(`SELECT a.*,s.name supplier_name,s.code supplier_code FROM approved_sources a JOIN suppliers s ON s.id=a.supplier_id WHERE a.project_id=? ORDER BY a.created_at DESC`).all(projectId);}
export function findProcurementOptions(projectId:string,componentId:string){requireProjectEntity("components",componentId,projectId);return db.prepare(`SELECT o.*,s.name supplier_name,s.code supplier_code,a.status approved_status FROM supplier_offers o JOIN suppliers s ON s.id=o.supplier_id LEFT JOIN approved_sources a ON a.offer_id=o.id AND a.project_id=o.project_id WHERE o.project_id=? AND o.component_id=? ORDER BY CASE o.availability WHEN 'in_stock' THEN 0 WHEN 'backorder' THEN 1 ELSE 2 END,o.unit_price ASC,COALESCE(o.lead_time_days,999999) ASC`).all(projectId,componentId);}
