import OpenAI from "openai";
import { randomUUID } from "node:crypto";
import { providerInfo,getClient } from "./providers.js";
import { EngineeringPlan } from "./engineering.js";
import { savePlan,saveRequirements } from "./engineering-db.js";
import { withAbortTimeout } from "./execution.js";
import { config } from "./config.js";
export const PLAN_SCHEMA=`{"id":"PLAN-xxxxxxxx","objective":"short engineering objective","assumptions":["explicit assumption"],"requirements":[{"id":"REQ-xxxxxxxx","description":"testable requirement","category":"functional|performance|mechanical|electrical|manufacturing|safety|environmental|cost|other","value":"optional string or number","unit":"optional unit","priority":"must|should|could","verificationMethod":"how the requirement will be verified","verificationStatus":"unverified"}],"steps":[{"id":"STEP-1","title":"step title","description":"concrete action","operationClass":"read|design|modify|export|manufacture","requiresApproval":false}],"expectedVerification":["observable evidence required for completion"]}`;
export const PLANNING_DECISION_SCHEMA=`{"action":"plan|clarify|none","message":"optional user-facing clarification or response","plan":${PLAN_SCHEMA}}`;
export type PlanningAction="plan"|"clarify"|"none";
export type PlanningContext={conversation?:Array<{role:"user"|"assistant";content:string}>;currentPlan?:unknown};
export type PlanningDecision={action:PlanningAction;message?:string;plan?:import("./engineering.js").EngineeringPlan};
export function buildPlanningPrompt(objective:string,constraints:string[],context:PlanningContext={}){const history=context.conversation?.slice(-12).map(item=>`${item.role.toUpperCase()}: ${item.content}`).join("\n")||"None";const currentPlan=context.currentPlan?JSON.stringify(context.currentPlan):"None";return`You are the planning layer of a local autonomous engineering factory. Decide whether the latest user request is ready for an engineering plan. You may choose not to create a plan yet.\n\nRules:\n- Use action=none when the conversation is casual, no engineering work is requested, or no useful action is being asked for.\n- Use action=clarify when an engineering goal is present but a missing detail is necessary to execute safely or correctly. Ask only the smallest useful clarification. Do not invent missing measurements or design intent.\n- Use action=plan when the request is sufficiently specified. Create the smallest conservative, testable plan.\n- A later user message can add information, correct an earlier requirement, or request a different change. Treat the latest request and conversation as authoritative and revise the current plan when needed. Do not preserve stale requirements merely because they appeared in an earlier plan.\n- If a current plan exists, update or replace it as necessary; do not blindly append a second unrelated plan.\n- Prefer deterministic verification. Manufacturing, physical actuation, irreversible export, or other consequential operations must require approval.\n- The plan is a planning artifact, not an execution transcript.\n\nReturn ONLY valid JSON matching this schema:\n${PLANNING_DECISION_SCHEMA}\nFor action=clarify or action=none, omit plan or set it to null. For action=plan, include a complete validated plan.\n\nLatest user objective/request:\n${objective}\n\nConstraints:\n${constraints.length?constraints.map(c=>`- ${c}`).join("\n"):"- None specified"}\n\nRecent conversation:\n${history}\n\nCurrent engineering plan, if any:\n${currentPlan}`;}
function extractJson(content:string):unknown{const trimmed=content.trim();try{return JSON.parse(trimmed);}catch{}const fenced=trimmed.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(fenced)return JSON.parse(fenced[1]);const start=trimmed.indexOf("{");const end=trimmed.lastIndexOf("}");if(start>=0&&end>start)return JSON.parse(trimmed.slice(start,end+1));throw new Error("Planner returned no JSON object.");}
const PlanningDecisionSchema={parse(value:unknown):{action:PlanningAction;message?:string;plan?:unknown}{if(!value||typeof value!=="object")throw new Error("Planner decision must be an object.");const candidate=value as Record<string,unknown>;const action=candidate.action;if(action!=="plan"&&action!=="clarify"&&action!=="none")throw new Error("Planner decision has an invalid action.");const message=candidate.message===undefined?undefined:String(candidate.message);const plan=candidate.plan===null||candidate.plan===undefined?undefined:candidate.plan;if(action==="plan"&&!plan)throw new Error("Planner action=plan requires a plan.");if(action!=="plan"&&plan)throw new Error(`Planner action=${action} must not include a plan.`);return{action,message,plan};}};
export function parseEngineeringPlan(content:string){const value=extractJson(content);if(value&&typeof value==="object"&&"action" in value){const decision=PlanningDecisionSchema.parse(value);if(decision.action!=="plan"||!decision.plan)throw new Error(`Planner decision is ${decision.action}, not a plan.`);return EngineeringPlan.parse(decision.plan);}return EngineeringPlan.parse(value);}
export function parsePlanningDecision(content:string):PlanningDecision{const value=extractJson(content);if(value&&typeof value==="object"&&"action" in value){const parsed=PlanningDecisionSchema.parse(value);return parsed.action==="plan"?{action:"plan",message:parsed.message,plan:EngineeringPlan.parse(parsed.plan)}:{action:parsed.action,message:parsed.message};}return{action:"plan",plan:EngineeringPlan.parse(value)};}
export function buildExecutionFallbackPlan(objective:string,constraints:string[]=[]){return EngineeringPlan.parse({objective,assumptions:["Planning provider was unavailable; execution is limited to deterministic factory capabilities and their verification evidence."],requirements:[{description:objective,category:"functional",priority:"must",verificationMethod:"deterministic factory capability result and post-operation verification"},...constraints.map(constraint=>({description:constraint,category:"other",priority:"must",verificationMethod:"deterministic capability validation and execution evidence"}))],steps:[{id:"STEP-1",title:"Execute the requested engineering change",description:"Use the smallest applicable deterministic factory capability, preserve explicit user dimensions, and verify the resulting state.",operationClass:"modify",requiresApproval:false}],expectedVerification:["Deterministic capability reports success and observable verification evidence matches the request."]});}
export function saveExecutionFallbackPlan(projectId:string,objective:string,constraints:string[]=[]){const plan=buildExecutionFallbackPlan(objective,constraints);savePlan(projectId,plan);saveRequirements(projectId,plan.requirements);return plan;}
function isClearlyActionable(objective:string){return /\b(create|make|build|design|change|modify|update|add|remove|cut|extrude|sketch|model|draw|generate|plate|box|cylinder|hole|enclosure|mount|bracket|component)\b/i.test(objective)||/\d+(?:\.\d+)?\s*(?:mm|cm|m|in|inch|inches|deg|°)/i.test(objective);}
export async function generateEngineeringPlan(projectId:string,objective:string,constraints:string[],context:PlanningContext={}){const info=providerInfo(),client=getClient();try{const response=await withAbortTimeout(signal=>client.chat.completions.create({model:info.model,temperature:0,messages:[{role:"system",content:"You produce strictly structured engineering planning decisions. Safety, current user intent, and verification take priority over speed."},{role:"user",content:buildPlanningPrompt(objective,constraints,context)}]},{signal}),config.PLANNER_TIMEOUT_MS,"Engineering planning");const content=response.choices[0]?.message?.content;if(!content)throw new Error("Planner returned an empty response.");const decision=parsePlanningDecision(content);if(decision.action!=="plan"||!decision.plan)return{decision,provider:info,fallback:false};const plan=EngineeringPlan.parse({...decision.plan,id:`PLAN-${randomUUID().slice(0,8)}`});savePlan(projectId,plan);saveRequirements(projectId,plan.requirements);return{decision:{...decision,plan},plan,provider:info,fallback:false};}catch(error){const message=String(error);if(/timed out|timeout|aborted/i.test(message)){if(!isClearlyActionable(objective))return{decision:{action:"clarify",message:"I need a concrete engineering request before I can create a plan. Tell me what you want to build or change, including the important dimensions or constraints."},provider:info,fallback:true,warning:"Engineering planner timed out; no plan was created because the request was not sufficiently actionable."};const plan=saveExecutionFallbackPlan(projectId,objective,constraints);return{decision:{action:"plan",plan},plan,provider:info,fallback:true,warning:"Engineering planner timed out; using a conservative deterministic execution fallback."};}throw error;}}
