import { providerInfo,getClient } from "./providers.js";
import { EngineeringPlan } from "./engineering.js";
import { savePlan,saveRequirements } from "./engineering-db.js";
import { withTimeout } from "./execution.js";
import { config } from "./config.js";
export const PLAN_SCHEMA=`{"id":"PLAN-xxxxxxxx","objective":"short engineering objective","assumptions":["explicit assumption"],"requirements":[{"id":"REQ-xxxxxxxx","description":"testable requirement","category":"functional|performance|mechanical|electrical|manufacturing|safety|environmental|cost|other","value":"optional string or number","unit":"optional unit","priority":"must|should|could","verificationMethod":"how the requirement will be verified","verificationStatus":"unverified"}],"steps":[{"id":"STEP-1","title":"step title","description":"concrete action","operationClass":"read|design|modify|export|manufacture","requiresApproval":false}],"expectedVerification":["observable evidence required for completion"]}`;
export function buildPlanningPrompt(objective:string,constraints:string[]){return`You are the planning layer of a local autonomous engineering factory. Convert the user's plain-language project request into a conservative, testable engineering plan. Do not invent measurements that the user did not provide. Turn explicit constraints into requirements. Prefer deterministic verification. Manufacturing, physical actuation, irreversible export, or other consequential operations must require approval. Keep the plan minimal and executable by downstream tools.\n\nReturn ONLY valid JSON matching this schema:\n${PLAN_SCHEMA}\n\nUser objective:\n${objective}\n\nConstraints:\n${constraints.length?constraints.map(c=>`- ${c}`).join("\n"):"- None specified"}`;}
function extractJson(content:string):unknown{const trimmed=content.trim();try{return JSON.parse(trimmed);}catch{}const fenced=trimmed.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(fenced)return JSON.parse(fenced[1]);const start=trimmed.indexOf("{");const end=trimmed.lastIndexOf("}");if(start>=0&&end>start)return JSON.parse(trimmed.slice(start,end+1));throw new Error("Planner returned no JSON object.");}
export function parseEngineeringPlan(content:string){return EngineeringPlan.parse(extractJson(content));}
export function buildExecutionFallbackPlan(objective:string,constraints:string[]=[]){return EngineeringPlan.parse({objective,assumptions:["Planning provider was unavailable; execution is limited to deterministic factory capabilities and their verification evidence."],requirements:[{description:objective,category:"functional",priority:"must",verificationMethod:"deterministic factory capability result and post-operation verification"},...constraints.map(constraint=>({description:constraint,category:"other",priority:"must",verificationMethod:"deterministic capability validation and execution evidence"}))],steps:[{id:"STEP-1",title:"Execute the requested engineering change",description:"Use the smallest applicable deterministic factory capability, preserve explicit user dimensions, and verify the resulting state.",operationClass:"modify",requiresApproval:false}],expectedVerification:["Deterministic capability reports success and observable verification evidence matches the request."]});}
export function saveExecutionFallbackPlan(projectId:string,objective:string,constraints:string[]=[]){const plan=buildExecutionFallbackPlan(objective,constraints);savePlan(projectId,plan);saveRequirements(projectId,plan.requirements);return plan;}
export async function generateEngineeringPlan(projectId:string,objective:string,constraints:string[]){const info=providerInfo(),client=getClient();try{const response=await withTimeout(client.chat.completions.create({model:info.model,temperature:0,messages:[{role:"system",content:"You produce strictly structured engineering plans. Safety and verification take priority over speed."},{role:"user",content:buildPlanningPrompt(objective,constraints)}]}),config.PLANNER_TIMEOUT_MS,"Engineering planning");const content=response.choices[0]?.message?.content;if(!content)throw new Error("Planner returned an empty response.");const plan=parseEngineeringPlan(content);savePlan(projectId,plan);saveRequirements(projectId,plan.requirements);return{plan,provider:info,fallback:false};}catch(error){const message=String(error);if(/timed out|timeout/i.test(message)){const plan=saveExecutionFallbackPlan(projectId,objective,constraints);return{plan,provider:info,fallback:true,warning:"Engineering planner timed out; using a conservative deterministic execution fallback."};}throw error;}}
